#+TITLE: Le méga donjon 2023 d’Orion
#+AUTHOR: Collectif du Discord d’Orion

* Introduction

Ce mégadonjon est une réalisation en cours sur le discord d’Orion
(https://discord.gg/orionjdr), vous pouvez venir nous rejoindre.

* Le donjons

** 1 : Entrée du donjon (nlegrand)

Sur l’escarpement d’un plateau, dans une vallée boisée, caché par la
végétation se trouve l’entrée d’une grotte d’environ cinq mètres de
large.

La grotte est fraîche et humide.

Le sol est fait de terre battue. Sur les côtés de la grotte on été
repoussé en vrac des ossements de nain. Les os portent des traces de
découpe.

La grotte se rétrécit en entonnoir sur 9 mètre pour arriver sur une
entrée de maçonnerie naine. Le linteau de l’ouverture portait des
inscriptions qui ont été grattées au burin. Dans l’arc de décharge se
trouvait une pierre qui a été abattue et se trouve brisée au sol,
poussée sur les côtés de l’entrée.

En reconstituant la pierre les connaisseurs de culture naine peuvent
reconnaître une représentation de Einbera Cuzziham, déesse de la forge
ainsi que les armes du royaume disparu de Dehukum.

L’entrée sans porte donne sur un sombre couloir maçonné au sol dallé
d’où on sent venir une légère odeur d’encens.

** 2 : Poste de contrôle (Yakurou)

Un couloir sombre de trente mètres, qui s'enfonce dans le sol.

Quatre encadrements, dont les portes ne sont plus présentes, donnent
accès sur 4 pièces distinctes.

Les deux premières ont été fouillées et retournées. On y trouve des
couchettes de bois, ainsi que des supports d'arme et des râteliers. Un
observateur averti pourrait trouver un compartiment caché derrière une
pierre du mur non scellé. À l'intérieur, un livre et deux pièces
d'or. La dernière page du livre est arrachée. Il recense les entrées
et sorties de l'endroit.

Dans la troisième et la quatrième pièce, on trouve des restes d'un feu
de camp. En fouillant un peu, on pourra trouver deux flèches oubliées
là, totalement utilisable. Leur manufacture est bien plus récente que
celle du bâtiment.

Une fois ces quatre portes passées, le couloir se pouesuit, toujours
aussi sombre, avec cette odeur d'encens qui semble vous inviter à
continuer

** 3 : Le hall (Webfourmi)

Le couloir se termine de façon abrupte par une volée de cinq marches
de pierre ébrechées et usées en leur centre.

Une grande pièce hexagonale d'une dizaine de mètres de diamètre aux
murs de pierre lisse et claire avec un haut plafond en coupole. Au
centre, un cercle de bronze poli d'un mètre de diamètre, légèrement
surelevé par rapport au sol . Le motif qui le décore est étrangement
disjoint.

Douze socles de statues vides forment un second cercle autour du centre.

Des ossements nains anciens et d'autres humains sont entassés dans un coin .

Après une fouille minutieuse de la pièce, on peut trouver Une courte
phalange portant encore une bague ornée d'une rune naine. (La même que
celle des anneaux d'ouverture).

Des torches consumées sont encore visibles dans leurs supports , deux à chaque mur.

Dès qu'elle est éclairée, la partie centrale du hall reflète la
lumière et semble s'en imprégner pour briller à son tour.

Un observateur attentif remarquera que les statues disparues ont été
sauvagement arrachées de leurs socles, comme en témoignent les traces
de burins qui blessent la pierre.

Il n'y a aucune trace de poussière au centre de la pièce.

Un héros curieux remarquerait que les trois cercles tournent et
peuvent aligner un motif de flamme ou un autre de rune naine ancienne
suivant leur agencement. Le premier motif enclenché,trois portes
cachées s'ouvrent sans bruit dans la paroi de roche, alors qu'au
second deux autres s'ouvrent alors que les premières se ferment.

Chaque paroi de l'hexagone ( sauf celle du couloir ) a une porte
dissimulée habilement.

L'odeur d'encens semble plus forte une fois les 2 dernières portes ouvertes.

** 4 : La galerie des ancêtres (Elwin)

Un des couloirs s'ouvrant après l'enclenchement de la rune est une
large galerie aux voûtes gothiques, aux murs ponctués de hautes
colonnes couvertes d'épitaphes et de cartouches à la gloire des
dynasties de Dehukum. Une odeur répugnante de charogne saisit les
visiteurs à la gorge.

Les torches révèlent des figures inquiétantes des deux côtés : les
masques mortuaires de tous les maîtres forges qui se sont succédés
ici. Leurs réussites les plus glorieuses sont célébrées sur chaque
pierre, soulignées par les citations élogieuses des monarques du
royaume et la longue litanie de leur cursus depuis leurs naissances.

La galerie se conclue par une haute porte de bronze verdie par les
années, encadrée par deux impressionnante statues de guerriers nains -
détail étonnant, sous les lourdes visières de pierre de véritables
crânes semblent se dessiner.

A leurs pieds se trouvent trois cadavres de nains en train de pourrir
dans une répugnante flaque marron.

Un sort de détection de la magie permet de trouver trois sources dans
la galerie :
- Un des masques mortuaires et les épitaphes associées sont une
  illusion : dessous se trouvent un autre texte dédié à un
  maître-forge dont le nom a été martelé. Son éloge semble révéler
  qu'il fut le plus brillant de tous, et l'inventeur de l'Ombrefer,
  alliage magique dont le secret s'est perdu depuis. Un graffiti
  hâtif, fait au charbon, le maudit lui et sa descendance sur 10
  générations pour ses crimes.
- Les deux statues sont magiques. Elles s'animeront et combattront
quiconque tentera de passer sans le mot de passe, introuvable
ici. Briser les crânes, bien protégés, permet de les vaincre plus
facilement.

La fouille des cadavres sera un moment désagréable et collant. Elle
révèlera qu'ils appartiennent à un clan dévoué à Hashbanik,
Celui-qui-anime, une divinité maléfique qui donne vie à leurs
constructs en y enfermant des âmes.

** 5 : Le puits des libations (Elwin)

La galerie des ancêtres s'ouvre sur une pièce rectangulaire au centre
de laquelle trône une rotonde taillée dans un marbre vert éclatant. Un
dôme de quartz au plafond déverse sur sa coupole une cascade de
lumière qui éclaire en retour toute la pièce d'une douce aura verte.

Le centre de la rotonde est occupée par un puits d'une facture
apparemment très ancienne, en gros appareil.

Les murs sont couverts de fresques rongées par l'humidité. Elles
illustrent les différents chapitres de l'histoire d'Einbera Cuzziham,
de sa naissance étrange à sa création des arts de la forge, en passant
par la légende du puits élémentaire. Pour s'allier les forces de l'eau
et se prémunir des ravages du feu, la déesse instaura le rite des
libations. Un peu d'eau versée sur une margelle, et une offrande en or
lancée dans le puits en retour.

Trois couloirs partent de la pièce, tous surmontés par le cartouche
d'une dynastie de maîtres-forgeurs différents. Ils mènent peut être
vers les tombeaux des artisans.

Quiconque jettera une offrande dans le puits gagnera Résistance aux
dégâts du feu, quoiqu'il ne se rendra pas compte tout de
suite. Quiconque ne jette pas d'offrandes avant de continuer dans les
tombeaux gagnera Sensibilité aux dégâts du feu, avec les mêmes
circonstances.  Le puits fait une dizaine de mètres de profondeur
avant de heurter la surface de l'eau. C'est un accès direct au plan
élémentaire de l'eau : qui s'y aventurerait risquerait très fort de ne
jamais trouver la surface - et encore moins les précédentes offrandes.

** 6 : Le tombeau hanté (Webfourmi)

Couloir sud du 5 puits des libations.

Les parois du couloir qui y mène sont sculptés . Des scènes de Forge
avec toujours le même nain. Malgré la dégradation des murs, un héros
déchiffrant le language runique nain lira : en hommage au Maitre de
Forge Thymmund Barbe d'or.

On débouche dans une pièce carrée, sans source de lumière au centre de
laquelle on voit un gisant de marbre. La pierre du dessus a été brisée
et le squelette dessous disloqué. Si un heros dérange le moindre
ossement, le spectre de Thymmund apparait et attaque avec un
magnifique marteau ouvragé.Vaincu, le fantôme disparait en hurlant
"Voleur !"

Le marteau du nain a été volé et se trouve quelquepart dans le
donjon. S'il est ramené dans la tombe, une cache s'ouvrira dans un des
murs revelant une armure complète avec heaume avec une CA +1 par
rapport à celle déjà portée(pour un héros nain s'il y en un, sinon
adapté au heros qui a reposé le marteau).

Le marteau de belle facture confère une résistance aux coups
contondants.

Si un héros le reprend après avoir pris le trésor, il sera maudit ( -1
Con / jour ) jusqu'à ce qu'un prêtre lève la malediction.
** 7 : Couloir des dragons (Elwin)
Couloir Ouest du puits des libations.

Les murs de ce long couloir sont percés de nombreuses alcôves, dans
lesquelles des squelettes de nains sont allongés. Devant chaque d'eux
se trouvent une petite coupelle vide et une lampe à huile éteinte -
ici reposent les nombreux apprentis et parents du maître-forge de
cette section. Certains possèdent quelques bijoux simples, mais de
valeur. Des personnages peu scrupuleux peuvent s'emparer ainsi de
bagues et de colliers pour une valeur d'une centaine de pièces
d'or. Ils feront toutefois du bruit qui avertira l'autre partie
présent dans la pièce plus loin - et suscitera sans doute l'hostilité
ultérieure de nains - vivants ou non.

Au terme du couloir se trouve une arche surmontée de deux statues de
dragons, gueules ouvertes et noircies. Le sol lui-même, entre eux, est
noirci. Selon la tradition Einbera Cuzziham avait dominé plusieurs
dragons rouges grâce au pouvoir des forces de l'eau, et c'est grâce à
leur feu qu'elle forgea les alliages les plus solides. Ce sont
manifestement ces puissantes créatures qui sont représentés.

Une détection de la magie signale que les deux statues sont
magiques. Quiconque les franchit déclenche immédiatement deux souffles
de feu, qui inflige des dégâts lourds, à moins de disposer d'une
résistance ou d'une immunité à ces dégâts.

** 8 : Magasin et stock (Yakurou)

Derrière une porte du Hall (pièce N°3) ouverte par la rune de flamme,
un petit sas entouré de deux portes, comportant les runes : "Danger :
Flamme nue interdite". Au sol, dans le sas, une dizaine de
lanterne. La plupart sont innutilisables, mais 2 d'entre elles peuvent
servir.

La seconde porte, pour sortir du sas, est coincée, il faudra forcer où
la détruire pour pouvoir passer. De l'autre côté, de grandes grilles
métalliques, où sont entreposer :

    - Des pioches, dont 5 sont encore utilisables ;
    - Des marteaux, dont 2 sont encore utilisables ;
    - Des casques de mineur, dont 3 sont encore utilisables ;
    - De nombreuses lanternes ;
    - 10 cordes de 20 mètres, dont 3 sont innutilisables ;
    - Des cages, avec un squelette d'oiseau dans chacune ;
    - Quantité de bois sec ;
    - De la poix.

(On peut trouver dans cette salle tout autre matériel nécessaire à vos
salle, ou tout ce qui peux être utiliser dans une mine Je modiefierais
au fur et à mesure.)

** 9 : Bureaux (Nicolas)

L’autre porte ouverte par la rune de flamme mène sur une grande salle
contenant quatre bureau de pierre taillés directement dans le gré rose
de la montagne. Chaque bureau a une inscription en rune naine de gravé
à l’avant :
- Paie ;
- RN (les érudits en culture naine reconnaîtront le sigle de Ressources Naines) ;
- Finances ;
- Secrétariat du directeur.

Derrière les bureaux on peut admirer de superbes mosaïques de
représentations de nains stakhanovistes dans les mines. Les mosaïques,
présentent de nombreuses citations en runes naines :
- Le travail c’est la santé ;
- La mine et le mineur sont les mamelles du peuple nain ,
- Travaillons jusqu’à la mort et au delà !

En fouillant la salle on peut trouver dans les tiroirs de nombreuses
fiches de paie, des contrats de fournitures pour la mine, un plan de
la mine (pas à jour), des formulaires de refus de congés, un code du
travail nain avec de nombreuses pages arrachées.

Au bout de la salle une embrasure qui a à la place d’une porte une
pierre de grés massive. On ne voit ni poignée ni charnière. Juste le
texte en rune naine dessus : « Bureau du directeur. Dites quelques
choses de plaisant pour entrer ». La porte s’escamote dans le mur
quand on dit quelque chose de plaisant. Laissez la s’ouvrir selon ce
que vous jugerez pertinent ou amusant dans les propositions des
joueurs, comme par exemple « je ne viens pas demander d’augmentation »
ou « à bas les 35 heures ! ».

** 10 : La forge (Webfourmi)

La dernière porte marquée de la flamme, la porte nord du Hall (3),
s'ouvre sur une vaste salle soutenue par de nombreux piliers
ouvragés. Le sol est dallé de marbre dont les nervures ont des reflets
d'or.

À l'ouest, 3 ouvertures obscures qui partent parallèles, avec des
rails qui courent dans les profondeurs. Un wagonnet de mine est à la
butée terminale de l'ouverture la plus au nord.

Une porte ouvragée au nord de la pièce et une autre a l'est.

Cinq postes de forges sont répartis dans la pièce. Un fourneau avec un
soufflet prêt à être rallummé. Les tuyaux des fourneaux s'enfoncent
dans le plafond pour rejoindre l'extérieur. Une enclume et un établi
avec tous les outils de la profession nécessaires.

Seuls manquent les métaux , rien à part quelques copeaux jonchant les
sols.

Des belles armes et armures qui ont été créees ici, ils n en reste que
les plans, des dessins savamment executés et précis que l'onpeut
trouver sur les établis .

Un héros compétent pourrait essayer de creer un de ces chefs d'œuvre à
condition qu'il trouve les matériaux.

Des créatures étranges ont élu domicile dans les conduits des
fourneaux. Elles attaquent dès qu'un heros s'approche à moins de
2m. Il y a 2 fois plus que de PJ. Ce sont des créatures ailées
d'envergure de 50cm, le cuir noir et crevassé parcouru de sillons
rougeâtres .On dirait de grandes chauves souris avec un visage deformé
de nain. Elles attaquent avec griffes et crocs et combattent jusqu'à
la mort. Elles ne sortent pas de la pièce.

Le cadavre de ces créatures révélera que c'étaient des nains , qui ont
été maudits et déformés par un sort de magie noire.

** 11 : La bibliothèque (KingBabylon)

Couloir Nord du 5 puits des libérations

Sur la paroi droite du couloir est gravé un pictogramme d'une flamme
barrée d'une croix. Sur la gauche, en rune naine, « Tout type de feu
est interdit ! ».  Si un héros entre dans la pièce avec une torche,
une voix féminine d'outre-tombe hurle : « Vous ne savez pas lire ?!
Foutez-moi le camp ! »

Cette pièce, toute en longueur, possède le même type de dôme en quartz
que la pièce précédente (la 5) permettant d'y voir clair sans avoir
besoin de torche.

La première chose qui attire l'œil est cette statue représentant une
naine sévère avec une énorme tresse. Sur laquelle, on peut lire,
toujours en langage runique nain, « Ci-gît notre bien-aimée architecte
en chef Katrin Tresse d'or. »

Les murs sont tapissés, du sol au plafond, d'étagères remplies de
livres. Étagères qui ne suffisent manifestement pas, on trouve
également des piles au sol. Attention à ne pas buter dedans, sans
quoi, Kratrin pourrait vous réprimander.

En fouillant dans les ouvrages, il est possible de trouver les
mémoires de Kratrin, les plans du donjon (du moins la partie connue
des nains), un livre de cuisine, des plans de forge, un herbier, un
livre d'énigmes, etc.

Attention, les livres sont à consulter sur place et ne sont pas
empruntables !

** 12 : La caldera (KingBabylon)

Prolongement ouest du 7

Après le porche avec les deux dragons au bout du couloir du même nom,
ce dernier se prolonge sur une dizaine de mètre et se termine en
donnant sur le cratère du volcan.

On présume qu'il n'est plus actif depuis des milliers d'années. Pour
preuve en son centre, une caldera s'est formée.  Les plus aventureux
en explorant le fond remarqueront un passage vers le niveau inférieur.

Quand la forteresse était encore en activité, le cratère servait de
piste d'attérissage. Ses dimensions font qu'il pouvait accueillir
plusieurs dragons et aéronefs en même temps.

** 13 : Salle des pifeuses ( Porte au nord de la forge (10)) (Yakurou)

Derrière la porte ouvragée, qui s'ouvre avec un grincement aigu, les
ténèbres. Des ténèbres que même une flamme ne pourrait éloigner.

On peut y entendre des pifeuses. Une espèce d'araignée mangeuse de
minerais bruts, dont se servaient les nains de l'époque pour
transmettre des messages du même principe que l'on utilise des pigeons
voyageurs. Celles-ci vivent dans les ténèbres les plus complet, et un
sort d'obscurité à été lancé sur la pièce.

Sauf que ces pifeuses n'ont pas vues d'être vivant depuis
longtemps. Tout geste brusque où toute lumière invoquée par les PJ les
rendrait agressives, et les fera attaquer. Les pifeuses s'enfuiront
dès le premier dégât subi, mais ces créatures sont rancunières, et
elles suivront les PJ pour les attaquer de nouveau au moment opportun.

Si les PJ donnent à manger aux pifeuses, celles-ci suivront le groupe
afin de recevoir d'autres rations.

Outre les pifeuses, les PJs pourront trouver dans ces lieux une énorme
clé (de la taille d'un nain) ainsi que deux portes, lapremière se
dirigeant vers le nord, la seconde vers l'ouest.

** 14 : La salle au trésor submergée (Webfourmi)

Porte nord de la salle des pifeuses

La porte est dure à ouvrir. Parce que des débris sont accumulés
derrière. Le plafond a été détruit et s'est effondré dans la salle
circulaire crevant le sol jusqu'aux étages inférieurs.

De nombreux restes de maçonnerie jonchent le sol . La pièce est
éclairée par l'extérieur. Une cascade dévale la paroi et se déverse
dans la pièce jusqu'au centre puis poursuit sa route dans le coeur du
donjon.  Le bruit de l'eau couvre les sons.

L'eau est pure et fraiche.

Des pies ont fait leurs nids dans les restes du plafond, on peut y
trouver des oeufs et trois bagues en or.

De nombreux coffres en mauvais état sont disséminés dans la salle. Un
PJ consciencieux finira par trouver un diadème d argent, et un collier
étrange avec une petite effigie de la déesse Einberra Cuzziham.

Des champignons poussent dans un coin. Certains sont luminescents et
peuvent servir d'éclairage d'appoint pendant 24h apres être
cuilli. Ils sont comestibles.

Les seules issues sont le trou dans le sol ou celui au plafond à 3m de
hauteur. Un PJ qui souhaiterait escalader devra faire un test
difficile, les parois sont rendues glissantes par l'humidité.

** 15 : Geôles (à l'ouest de la salle des pieuses (13)) (Yakurou)

Derrière cette porte usée, autrefois fermée par de nombreux verrous
aujourd'hui hors d'usage, se trouve des Geôles.

Une dizaine de cellules exigüe, où attendent maintenant des
squelettes.

Deux autres sorties à ces lieux. Une au nord, et une autre à l'ouest.

Au-dessus de la porte ouest, le plafond s'est effondré. À l'intérieur
d'une des cellules, accolant au mur ouest, une autre sortie a été
creusé à travers le mur. Avec des connaissances dans le domaine, on
pourra dire que le mur a été creusé à partir de l'autre pièce, par des
personnes qui, semble-t-il, souhaitaient arriver ici.

La porte nord était également fermé par de nombreux verrous, aucun ne
fonctionne encore à l'heure actuelle.

Dans la pièce, des fantômes de nain sont présents. Il semble perdu,
tous cherchent à se repentir, même si aucun ne semble se souvenir de
la faute qu'il a commise.

Les squelettes ne datent pas tous de la même époque. Et l'un d’eux est
même habillé avec des vêtements très récents. On peut y trouver celui
d'une humaine.

** 16 :  L'ascenseur (porte nord ouest du hall(3)) (KingBabylon)

La pièce fait environ 3 mètres sur 3. Au centre, une armature en bois
de 2 mètres sur 2.

Deux chaines traversent de haut en bas cette armature. En tirant celle
de droite, cette boite se déplace vers le bas pour accéder aux étages
inférieurs. Celle de gauche permet de monter.

Gravés à l'intérieur, sur le bois, 4 nains barrés d'une croix.

** 17 : La salle d'eau (à l'est de 10) (KingBabylon)

c'est une grande salle, deux fois comme la forge. 

À la moitié de la pièce, sur toute la largeur, quelques marches
permettent de descendre. Selon toute vraisemblance, cet espace devait
servir de bain. On y voit un tuyau qui coure le long de la zone. Tuyau
trouvant sa source dans la forge.

Sur les murs, des potences avec des restes de vêtement. 

4 puits sont répartis dans la salle. Un seul est encore en état de
fonctionnement. C'est un mécanisme à manivelle permettant
d'enrouler/dérouler la chaîne. Totalement enroulée, on voit que la
chaîne fait une dizaine de mètres.  Un personnage regardant au fond ne
verra rien. Mais en y laissant tomber un objet, il mettra un certain
temps à toucher le fond dans un bruit d'eau.  S'il tente une descente
en utilisant la chaîne, il faudra faire un test pour éprouver la
solidité du mécanisme. Lors de sa descente, il aura accès aux étages
-1 et -2 avant d'atteindre le -3 qui est une grande réserve d'eau.

** 18 : Salle de dissection/ torture (Webfourmi)
Au nord des geôles (15)

Une salle rectangulaire au sol et aux murs de pierre. Une autre
ouverture à l'ouest et une au nord fermées par de lourdes portes
renforcées.

Une table de pierre avec des chaînes aux extremités et des rigoles
d'écoulement.  Une grille scellée au sol juste a côté.  Un établi avec
des instruments de torture rouillé.

Une cage accrochée au plafond dans un coin. Au sol de cette cage un
coeur brisé gravé dans le métal.

Une étagère avec de vieux grimoires d'anatomie poussiéreux. 

Une lettre est cachée à l'intérieur. 
Qu'un PJ curieux pourrait trouver

« Je te pardonne Griselda. Je sais que tes expériences sont plus
importantes que tout. Je ne survivrai pas à la prochaine, la maladie
est trop avancée et malgré tes soins, je vais mourir. Je t'offre mon
dernier cadeau : étudie mon corps pour trouver un remède.

Adieu, mon âme attendra la tienne dans l'au-delà.

Artelus. »

** Salle 19 : Le bureau du directeur
*** La Salle
Une grande salle carrée large comme la précédente avec des plafonds de
10 m de haut. Les murs sur les côtés sont recouverts de tiroirs. Les
tiroirs contiennent tous les contrats, contrats de travail, fiche de
paie et dossiers administratifs de la mine. Au fond de la salle un
gigantesque bureau devant un énorme fauteuil. Sur le fauteuil un
squelette de nain richement vêtu à l'air triste. Derrière le fauteuil,
un gigantesque bas relief représentant Einbera Cuzziham, déesse de la
forge, portant dans une main un marteau, dans l'autre un soufflet
portant les armes du royaume disparu de Dehukum. Les yeux et la bouche
de la déesse sont des chasses vides qui devaient contenir des pierres
précieuses. Derrière le bureau se trouve plusieurs coffres incrustés
dans le mur.
*** Convoitise
Posé sur le bureau, devant le squelette une double hache de guerre
impressionnante joliment ouvragée. elle contient plusieurs chasse qui
semblent pouvoir contenir des gosses pierres précieuses. Convoitise
est une arme consciente avec un bonus à l'attaque et au dégât. En
revanche, elle attise le besoin de richesse de son porteur, ce dernier
doit réussir un jet (volonté/sagesse) pour se désengager d'un combat
dont l’issue pourrait lui être profitable. Convoitise a beaucoup de
dédain pour les adversaires pauvres, mais accepte de les tuer par
respect pour son porteur. Si le porteur fuit un combat profitable, il
aura désavantage à tous ses jets avec convoitises. Si on ajoute des
pierres magiques à convoitise, son bonus à l'attaque et au dégâts
augmente, ainsi que la difficulté à fuir un combat profitable. Des
petits tuyaux servant aux déplacement des piffeuses débouchent dans la
pièces.
*** Regdrum Garbek
Regdrum Garbek était déjà mort quand la mine était en activité. Il n'a
pas voulu quitter son poste et personne n'a osé le lui demander. C'est
un redoutable squelette très dur à duper ou à battre. Et pourtant, il
se lamente, il s'est fait flouer par Isifor-Mercadel le Fourbe, voleur
Halfelin qui l'a convaincu de lui prêter les trois pierres pour
débarrasser la mine de ses gobelins. Désormais, ces dernières sont
dispersées dans la mine au grand malheur de Regdrum qui ne peut
quitter son bureau.

Regdrum peut proposer aux joueurs un contrat pour récupérer les trois
pierres. Il est prêt à donner l'équivalent de mille pièces d'or en
gemme pour chaque pierre. Il sera prêt à prêter convoitise si cette
dernière est nécessaire pour abattre un ennemi puissant, avec un
contrat obligeant à sa restitution évidemment. Les contrats de Regdum
sont enchantés et une fois signés, ils obligent les
contractants. C'est est une bonne nouvelle, parce que sans ça, il y
aurait peu de chance que Regdrum accepte de donner des richesses aux
gens à qui il les doit, cela ne l'empêche pas en revanche de geindre
et se lamenter à chaque centime dont il se sépare. On peut rompre le
contrant en réussissant un jet de volonté très difficile. Le joueur
qui rompt le contrat aura désavantage à tous ses jets pendant un jour.

Regdrum a su conserver la fidélité de quelques piffeuses qui peuvent
transporter ses messages dans toute la mine.

Regdrum aime les gens qui travaillent jusqu'à en mourir. Il déteste
les congés en général. Il n'a jamais entendu parler des congés payés,
mais pour lui c'est un tel blasphème que si on en parle il entrera
dans une colère noire où il pourra tuer les gens se trouvant devant
lui. Il se plaint tout le temps qu'on cherche à le déposséder et qu'on
s'acharne à vouloir le jeter dans la misère et la pauvreté.
*** Les trois pierres
- Dazun, le rubis du feu, donne un bonus de force à son porteur, ou
  augmente le pouvoir de convoitise ou réactive le volcan et la forge
  enchâssé dans la statue de la déesse de la forge et donne accès à
  des salles du donjon inaccessibles sinon ;
- Zabun, le saphir de l'eau, donne un bonus de constitution à son
  porteur, ou augmente le pouvoir de convoitise ou réactive les
  rivières souterraines qui alimentent la forge enchâssé dans la
  statue de la déesse de la forge et donne accès à des salles du
  donjon inaccessibles sinon ;
- Grizzun, l'émeraude électrique, donne un bonus d'agilité à son
  porteur, ou donne à Convoitise le pouvoir de lancer des éclairs (et
  augmente la difficulté de fuir un combat profitable) ou réactive le
  circuit de wagonnet de la mine enchâssé dans la statue de la déesse
  de la forge, tout wagonnet sera mue par une énergie propre et
  permettra de se déplacer dans toute la mine, dont dans des zones
  inaccessibles sinon.

Les trois pierres, ainsi que Convoitise sont enchantés et ne peuvent
être sorties de la mine.

*** Trésor 

Les trésors cachés derrière Regdrum Garbek sont incommensurable. Mais
il faut pour les obtenir duper ou vaincre Regdrum, ce qui est
improbable et il faudra ensuite passer les multiples protections de
chacun de ces coffres.
